# Generated by Django 5.2.1 on 2025-07-23 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.TextField()),
                ('event_duration', models.DurationField()),
                ('event_language', models.CharField(default='Hindi', max_length=50)),
                ('event_age_limit', models.PositiveIntegerField(default=0)),
                ('event_genres', models.CharField(default='General', max_length=100)),
                ('event_time', models.TimeField()),
                ('event_about', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
