# Generated by Django 5.2.1 on 2025-07-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventdetail_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='event_duration',
            field=models.CharField(default='0:00:00', max_length=50),
        ),
    ]
