# Generated by Django 5.2.1 on 2025-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_event_location_event_age_restriction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='interested_count',
        ),
        migrations.AddField(
            model_name='event',
            name='artists_images',
            field=models.ImageField(blank=True, null=True, upload_to='events/artists/'),
        ),
        migrations.AddField(
            model_name='event',
            name='artists_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
