# Generated by Django 5.2.1 on 2025-07-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=70)),
                ('album_type', models.CharField(max_length=70)),
                ('album_image', models.ImageField(default='', upload_to='products')),
            ],
        ),
    ]
