# Generated by Django 5.2.1 on 2025-07-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='albums',
            new_name='Album',
        ),
    ]
