# Generated by Django 5.2.1 on 2025-07-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_rename_albums_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.ImageField(upload_to='album_images/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(max_length=50),
        ),
    ]
