# Generated by Django 5.2.1 on 2025-07-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='movie_name',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
    ]
