# Generated by Django 5.2.1 on 2025-07-14 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_song_duration_song_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=180)),
        ),
        migrations.AlterField(
            model_name='song',
            name='movie_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
