# Generated by Django 5.2.1 on 2025-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_song_duration_alter_song_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_image',
            field=models.ImageField(blank=True, null=True, upload_to='song_images/'),
        ),
    ]
