# Generated by Django 5.2.1 on 2025-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0008_song_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
