# Generated by Django 5.2.1 on 2025-07-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_album_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='audio_file',
        ),
    ]
