# Generated by Django 5.2.1 on 2025-07-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_remove_album_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredalbum',
            name='slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_slides/'),
        ),
    ]
