# Generated by Django 5.2.1 on 2025-07-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_sounds', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='albums',
        ),
    ]
