# Generated by Django 5.2.1 on 2025-07-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Events', 'Events & Press'), ('Festivals', 'Festivals'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], default='Music', max_length=100),
        ),
    ]
